### ISSUE TITLE
Docker daemon runs as root, writing to volume mounts leaves files unreadable for buildkite-agent

### ISSUE THREAD

**Issue by lox** [buildkite/buildkite-aws-stack#30]
If builds run docker commands and mount in volumes, files are written as root, due to Docker's root-only-ness. 

This means that subsequent builds fail with permission errors because they can't `git clean` the files.

**Comment by lox** [comment]
More details here https://github.com/docker/docker/issues/3124

**Comment by jeromegn** [comment]
I just stumbled on this very issue. My workaround is to build an image ADDing the files instead of mounting a volume on a generic image.

**Comment by lox** [comment]
A terrible hack that we have as a workaround is to use the docker socket to chown the files in a `post-command` hook:

```
#!/bin/bash
set -eu

docker run -it -v $(pwd):/project busybox chown -R 498.496 /project
```
