### ISSUE TITLE
Add support for other aws regions

### ISSUE THREAD

**Issue by mikekap** [buildkite/buildkite-aws-stack#44]
It would be nice to launch these in e.g. us-west-2 in my case.

**Comment by toolmantim** [comment]
@mikekap @deoxxa this is now live, you can now use the stack in:

* us-west-1
* us-west-2
* eu-west-1
* eu-central-1
* ap-northeast-1
* ap-northeast-2
* ap-southeast-1
* ap-southeast-2
* sa-east-1

**Comment by deoxxa** [comment]
Excellent! Thank you!
