### ISSUE TITLE
Autoscaling policies can livelock at 0 runners

### ISSUE THREAD

**Issue by mikekap** [buildkite/buildkite-aws-stack#46]
When using the job based autoscaling, you can get into a (common) situation where there aren't any executors (so `RunningJobsCount == 0`), and there are queued jobs (so `ScheduledJobsCount > 0`). Then whenever the scale up hook adds a server, in the time it takes for the server to boot, the scale down hook kills it.

**Comment by lox** [comment]
This should be fixed with the recent changes to scale both up and down on `ScheduledJobsCount`.
