### ISSUE TITLE
RFC: Improving cold cache for large no. of parallel jobs w/ autoscaled instances

### ISSUE THREAD

**Issue by toolmantim** [buildkite/buildkite-aws-stack#74]
If you have a Rails app that takes a long time to do a `docker build` on a fresh machine, and a pipeline with 50+ parallel spec steps, and an auto-scaling group that goes from 0 to x, having cold Docker caches can be a total bummer. This is because each of the `test` steps ends up running `docker-compose build` which can take a huge amount of time for non-trivial apps… basically creating these massive outlier build times that developers would tear that hair out over.

Now you can use the beta buildkite agent and https://github.com/buildkite/docker-compose-buildkite-plugin you're able to add a "build" step at the start of the pipeline and have all subsequent steps pick up this built docker image, instead of having to build it again on all your machines. This is very similar to how most people would structure their own pipelines anyhow, and it means you end up pushing a Docker image somewhere for each build which is also nice for later debugging. And it works with the docker hub credentials support that's already built into this stack. For example:

```yml
- command: build-and-push.sh
- wait
- command: parallel_spec.sh
  name: "Spec %n"
  parallelism: 50
```

The way I'm doing this at the moment is by creating two separate CloudFormation stacks: `buildkite-builders` and `buildkite-runners`. `buildkite-builders` is a t2.medium with a min size of 1 and max size of 2 and scale-in/scale-out of 0 to disable auto-scaling (you can't have it min 1 max 1, or else stack updates fail because of the stack update policy that requires at least one instance to be in service). `buildkite-runners` is a c4.medium with spot pricing, min size of 0, max size of 50, scale-out/in of +-25. This setup means you get an always-on warm cache for building+pushing, and relatively fast spin up for runners for the parallel tests (fast in both auto-scaling, and in terms starting the job on a new instance). This keeps most builds < 5 minutes if there's enough agents, or an extra few minutes if new agents need to be spun up.

I think this sort of thing is a pretty common pattern, and it'd be nice to build this into the stack somehow.

One idea would be to enable you to set a fixed size of "builders" instances which stay on at all times, which end up with their own queue which you can target using the new docker plugin. It could be that for a given stack you end up with `{stack-name}-builders` and `{stack-name}-runners`. There would be no auto-scaling of builders (but they could still be managed via an ASG). If we built this into the own stack, you'd end up with parameters to configure the two different ASGs, builders and runners.

**Comment by toolmantim** [comment]
Comments / suggestions @lox @Vektah @bgentry @bjeanes @sj26 @keithpitt @chendo @BlakeMesdag @es ? We’re so close to having a pretty powerful out-of-the-box solution for existing slow apps. Just creating two separate stacks works fine now, but if having a builder is such a common pattern I think it'd make sense to support it as part of the stack. It also means you only have a single CF stack to keep up-to-date.

**Comment by bjeanes** [comment]
Working late? :)

**Comment by bjeanes** [comment]
I love this idea. I think I need to play with this to get a feel for how it would work in my situation (not many devs, not many builds at a time... for now) but in principle it seems like a really great complement to BK. BK not running builds directly is both a value and an obstacle. Having a really 👌 low-touch runner setup to pair that is mostly click-to-run but on their own infrastructure seems like a match made in heaven!

**Comment by lox** [comment]
Could this just be done as a nested stack with some good defaults?

**Comment by toolmantim** [comment]
@lox oh yeah! `docker-builder-stack` It'd need to use the same AMI mappings, which we could pass through I assume?

**Comment by Vektah** [comment]
This seems like tuning for a very specific (but common) use case.

An alternative would be to keep EBS volumes around and reattach  them at startup. Provides the 'builder' stability on any instance. If the first instance had a builder tag it would have all of the advantages above but also speed up builds on the whole

**Comment by mdub** [comment]
This does sound very specific to the way you're using docker-compose, and caching per-build images in a Docker registry.  I'd say "overly" specific, in fact.

I do see value in being able to support multiple ASGs of agents, for various reasons:
- support different instance-sizes or capabilities (IAM, SSH creds, etc)
- support a mix of always-on on-demand instances (for quick start, and to keep caches warm) and spot-priced instances (for cheap extra capacity)

But, I not sure they need to be in the same stack, when spinning up multiple stacks is so easy.

**Comment by lox** [comment]
> But, I not sure they need to be in the same stack, when spinning up multiple stacks is so easy.

I keep coming back to this. If we could offer some nested stacks to automate this, sure, but I'd be reluctant to add a lot of complexity to the basic stack.

**Comment by BlakeMesdag** [comment]
This is very specific to Docker Compose, which is a good start. A more generic approach would be to allow synchronous agent steps to inject environment variables into subsequent steps. This would allow you to pass on information to your runner steps without being tied directly to a specific container runtime. 

Currently you can achieve this using pipeline uploads, but those come with certain tradeoffs (race conditions, harder to track immediate runner needs etc).

**Comment by lox** [comment]
@BlakeMesdag Or alternatively allowing steps to define dependent steps that must have run before them, with some guarantees around metadata read-after-store. I'd guess the docker-compose solution just adds some boilerplate the copies around images though, I doubt there is anything docker-compose specific?

**Comment by toolmantim** [comment]
@BlakeMesdag @lox yeah there's nothing Docker Compose specific about this setup, that all lives in the https://github.com/buildkite/docker-compose-buildkite-plugin This was more wanting to know if there should be an easier way to setup `builder` and `runner` machines for a docker-compose type setup (`[build + push] [wait] [pull + run tests, parallelism: n]`).

But I think we should leave this as is based on feedback… keep it as "one stack == one agent queue". For the builder + runner use case we can solve it with documentation, and guide people on how to setup the two separate stacks, agent meta-data and pipeline.yml configurations…

**Comment by toolmantim** [comment]
Thanks everyone for taking the time to add your feedback! Super helpful.

**Comment by toolmantim** [comment]
Something like this to warm up CI nodes, backed by S3, might actually be better… http://blog.runnable.com/post/145362675491/distributing-docker-cache-across-hosts

**Comment by bjeanes** [comment]
That's interesting. Using a BitTorrent Sync agent to distribute caches reminded me of how Twitter deploys (or used to) using Bittorrent to distribute artefacts to all their hosts: https://blog.twitter.com/2010/murder-fast-datacenter-code-deploys-using-bittorrent. Cute idea...
